#ifndef SYNCCOM_PUBLIC_H
#define SYNCCOM_PUBLIC_H

#ifdef __cplusplus
extern "C"
{
#endif
#include <string.h>

#define SYNCCOM_REGISTERS_INIT(registers) memset(&registers, -1, sizeof(registers))
#define SYNCCOM_UPDATE_VALUE -2
#define STATUS_LENGTH 2
#define NUM_CLOCK_BYTES 20

typedef INT64 synccom_register;

struct synccom_registers {
	synccom_register __reserved1[2];
	synccom_register FIFOT;
	synccom_register __reserved2[2];
	synccom_register CMDR;
	synccom_register STAR; /* Read-only */
	synccom_register CCR0;
	synccom_register CCR1;
	synccom_register CCR2;
	synccom_register BGR;
	synccom_register SSR;
	synccom_register SMR;
	synccom_register TSR;
	synccom_register TMR;
	synccom_register RAR;
	synccom_register RAMR;
	synccom_register PPR;
	synccom_register TCR;
	synccom_register VSTR; /* Read-only */
	synccom_register __reserved4[1];
	synccom_register IMR;
	synccom_register DPLLR;
	synccom_register FCR;
};

struct synccom_memory_cap {
	int input;
	int output;
};

enum transmit_modifiers { XF = 0, XREP = 1, TXT = 2, TXEXT = 4 };


#define SYNCCOM_IOCTL_MAGIC 0x8018
#define SYNCCOM_IOCTL_INDEX 0x800

#define SYNCCOM_GET_REGISTERS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_SET_REGISTERS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+1, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_PURGE_TX CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_PURGE_RX CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+3, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_ENABLE_APPEND_STATUS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_DISABLE_APPEND_STATUS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_GET_APPEND_STATUS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+13, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_SET_MEMORY_CAP CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_GET_MEMORY_CAP CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+7, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_SET_CLOCK_BITS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+8, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_ENABLE_IGNORE_TIMEOUT CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+10, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_DISABLE_IGNORE_TIMEOUT CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+11, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_GET_IGNORE_TIMEOUT CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+15, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_SET_TX_MODIFIERS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+12, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_GET_TX_MODIFIERS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+14, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_ENABLE_RX_MULTIPLE CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+16, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_DISABLE_RX_MULTIPLE CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+17, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_GET_RX_MULTIPLE CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+18, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_ENABLE_APPEND_TIMESTAMP CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+19, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_DISABLE_APPEND_TIMESTAMP CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+20, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_GET_APPEND_TIMESTAMP CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+21, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_ENABLE_WAIT_ON_WRITE CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+22, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_DISABLE_WAIT_ON_WRITE CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+23, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_GET_WAIT_ON_WRITE CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+24, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SYNCCOM_TRACK_INTERRUPTS CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+25, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define SYNCCOM_GET_MEM_USAGE CTL_CODE(SYNCCOM_IOCTL_MAGIC, SYNCCOM_IOCTL_INDEX+26, METHOD_BUFFERED, FILE_ANY_ACCESS)

#ifdef __cplusplus
}
#endif
#endif
